apiVersion: apps/v1
kind: Deployment
metadata:
  name: detectorapp
  labels:
    app: detectorapp
spec:
  selector:
    matchLabels:
      app: detectorapp
  template:
    metadata:
      labels:
        app: detectorapp
    spec:
      containers:
      - name: detectorapp
        image: muhammadqadora/detector
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: detectorapp
  ports:
  - port: 8081
    targetPort: 8080
  type: LoadBalancer
