apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: db
                name: myconfig
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: mysecret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysecret
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: 'True'
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
